### ISSUE TITLE
many many warning using defaults for npm install

### ISSUE THREAD

**Issue by b-r-s** [angular-guru/electron-seed#1]
Hi There,
   Many kudos for putting together 'electron-builder' and this example.  However, using git clone on the example, and running npm install with no modifications issues quite a few vulnerabilities
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

added 1134 packages from 1297 contributors and audited 43783 packages in 546.818s
found **114 vulnerabilities (12 low, 52 moderate, 49 high, 1 critical)**

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

I've attached the full output of the install process.

[electron-builder-install-issues.docx](https://github.com/angular-guru/electron-seed/files/3194726/electron-builder-install-issues.docx)

My main concern is how important all these warnings are going forward - and I do realize that a lot of them are not under your control.

Nonetheless - after building, npm start displayed only a blank page and the following error in chrome dev tools 

Uncaught ReferenceError: require is not defined
    at Object.url (external "url":1)
    at __webpack_require__ (bootstrap:76)
    at Object.<anonymous> (client:6)
    at Object../node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:0 (vendor.js:72506)
    at __webpack_require__ (bootstrap:76)
    at Object.0 (main.ts:11)
    at __webpack_require__ (bootstrap:76)
    at checkDeferredModules (bootstrap:43)
    at Array.webpackJsonpCallback [as push] (bootstrap:30)
    at main.js:1

Again - I was truly excited to find your solution as it's been a true pain getting Angular and Electron working together smoothly ( mostly due to no support for 'require('foo') issues ) 

Any advice is most welcome and appreciated
thanks in advance
b  :)

**Comment by ashh640** [comment]
Hi! Thanks very much for the feedback. I did recently release a new version of electron builder however I have just realised I have neglected to update this seed project.

The project has package-lock.json file present so it likely isn't using the latest version of electron builder. You should be able to run 'npm install @angular-guru/electron-builder@latest' to update the library.

In regards to the other security issues etc. I recommend updating to the latest version of Angular which should mitigate most of these. This should be very straightforward by following the steps at https://update.angular.io. If any still remain the 'npm audit' command should be able to get rid of them.

I will keep this issue open and try to make the fix as soon as I get time. If you have any issues try creating a brand new project with the Angular CLI and following the steps to add electron builder manually, it should be very straightforward: https://github.com/angular-guru/electron-builder/blob/master/README.md

Thanks for your feedback and apologies for the inconvenience.

**Comment by ashh640** [comment]
Ok, I just took a look into the issue and it looks like there may be more to the problem that I first thought. It looks like some internal API has possibly changed.

It's likely electron builder will need quite a bit of work now that the Angular CLI builders api has stabilised with Angular 8.

I recommend taking a look at this project which may help you achieve what you need as this doesn't look like it'll be a quick fix for me: https://github.com/BenjaminDobler/ngtron

**Comment by b-r-s** [comment]
HI -  many thanks for such a quick response - looks like I opened a "can of worms" for you ;)
I appreciate your suggestion and I'll look at "ngtron" to see how it fares.
Best of luck with your fixes.
b  👍  :)

**Comment by ashh640** [comment]
Turns out that Electron 5 had changed the default `nodeIntegration` property to false. I have updated the project and it should now work as expected and have no more security vulnerabilities

**Comment by b-r-s** [comment]
good stuff :) - I'm currently using 7.2nnn - is that what you mean by the latest ? - or do you mean the not yet official version 8 ("Ivy").  The link you gave me previously [https://github.com/BenjaminDobler/ngtron] has a disclaimer that it requires v8 
In the meantime I'm going to try your update against v7.2

thanks again
b

**Comment by ashh640** [comment]
I have updated this project to use the latest 7.2 version of Angular so that should hopefully work for you without having to use any pre-release versions.

**Comment by b-r-s** [comment]
Hi Ashley - I replied on-line before I got this email.

   I'm trying out your new version and so far so good :

      Initial install of 'Electron-Builder' => Perfect



   npm install for the "test" project => Perfect


     npm run electron => Perfect




    great work and thanks again - I have not yet tried to actually work 
with Electron in this test yet, but it's looking for good  :)
b

------ Original Message ------

**Comment by ashh640** [comment]
Excellent! Thanks very much for your feedback! In regards testing, you'll likely need to use a third party plugin like karma-electron to launch the tests inside the electron window, but it should allow you to build with the correct settings.

Thanks again!

**Comment by b-r-s** [comment]
Hi Again ,

    I've got my app pretty much re-built and although all seems good - no 
errors or warnings of any type - when I "npm run electron", I initially 
get only a blank screen, with the default Electron menu.  I then have to 
click "reload" from that menu at which time my app pops up immediately.

  Safe to assume this is not the way it should be ;) ...

    Any thoughts are much appreciated.

thanks again
b

------ Original Message ------

**Comment by brucebrit** [comment]
I also have this issue "Uncaught ReferenceError: require is not defined". So is the fixed done?
